---
- hosts: ose
  tasks:
      - name: package epel-release upgrade
        yum: name=epel-release
      - name: Install docker
        yum: name=docker state=present
      - name: Copy script file
        copy:
           src: /root/1sarvani/git-repos/ansible/osetraintsk/oseinstall1.sh
           dest: /root
           owner: root
           mode: 0744
      - name: Execute script to add INSECURE_REGISTRY to sysconfig docker file
        script: oseinstall1.sh >> logfile.log
      - name: Enable and start docker
        service: enabled=true name=docker state=started
      - name: Copy script file
        copy:
           src: /root/1sarvani/git-repos/ansible/osetraintsk/oseinstall.sh
           dest: /root
           owner: root
           mode: 0744
      - name: Execute script to install oc cluster and change the working directory to scripts/ before executing the command.
        shell: oseinstall.sh >> logfile.log
