---
- hosts: test
  tasks:
      - name: package epel-release upgrade
        yum: name=epel-release
      - name: Install docker
        yum: name=docker state=present
      - name: Copy script file
        copy:
           src: /root/1sarvani/git-repos/ansible/osetraintsk/oseinstall1.sh
           dest: /root
           owner: root
           mode: 0744

      - name: Insert docker INSECURE_REG line
        lineinfile: 
          path: /etc/sysconfig/docker
          state: present
          insertafter: EOF
          line: "INSECURE_REGISTRY='--insecure-registry 172.30.0.0/16'"
        notify: restart docker

      - name: Enable and start docker
        service: enabled=true name=docker state=started
      #- name: Copy script file
      #  copy:
      #     src: /root/1sarvani/git-repos/ansible/osetraintsk/oseinstall.sh
      #     dest: /root
      #     owner: root
      #     mode: 0744
      #- name: Execute script to install oc cluster and change the working directory to scripts/ before executing the command.
      #  script: oseinstall.sh >> logfile.log

      
      - name: Check if oc is installed, if not, install
        stat: path='/usr/local/bin/oc'
        register: sym
      
      - debug: msgi="islnk isn't defined (path doesn't exist)"
        when: sym.stat.islnk is not defined
      
      #- name: install ose when sym link is not defined
      - name: Create a folder in tmp
        file: path=/tmp/1sarvani state=directory
        when: sym.stat.islink is not defined

      - name: wget the oc install
        get_url:
            url: https://github.com/openshift/origin/releases/download/v1.5.0/openshift-origin-client-tools-v1.5.0-031cbe4-linux-64bit.tar.gz
            dest: /tmp/1sarvani
        when: sym.stat.islink is not defined

      - name: tar - unzip the oc tar
        unarchive:
            src:  /tmp/1sarvani/openshift-origin-client-tools-v1.5.0-031cbe4-linux-64bit.tar.gz
            dest: /tmp/1sarvani
            remote_src: yes
        when: sym.stat.islink is not defined

      - name: Move to usr local bin
        shell: cp -r /tmp/1sarvani/openshift-origin-client-tools-v1.5.0-031cbe4-linux-64bit/ /usr/local/bin/
        when: sym.stat.islink is not defined
 
      - name: oc cluster up
        script: oc cluster up
      
      
      
      
  handlers:
   - name: restart docker
     service: name=docker state=restarted      #http://docs.ansible.com/ansible/latest/apache2_module_module.html
